name: Rust Format and Lint

on:
  push:
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  rust_checks:
    name: Rust checks (fmt + clippy)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy -- -D warnings
